import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Tab from "@/component/Tab";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  display: 'swap'
});


export const metadata: Metadata = {
  title: "Eyeline Optica",
  description: "Generated by create next app",
  
  metadataBase: new URL('https://www.eyelineoptica.com'), 

  authors: [{ name: 'INJAMAM ISLAM CHOWDHURY', url: '/humans.txt' }],
  
  other: {
    'link[rel="author"]': '/humans.txt', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Header/>
        <Tab/>
        {children}
      </body>
    </html>
  );
}