import demo1 from "../../public/images/glass-1.png";
import demo2 from "../../public/images/glass-2.png";
import demo3 from "../../public/images/glass-3.png";
import demo4 from "../../public/images/glass-4.png";
import demo5 from "../../public/images/glass-5.png";
import demo6 from "../../public/images/glass-6.png";
import demo7 from "../../public/images/glass-1.png";
import demo8 from "../../public/images/glass-2.png";
import demo9 from "../../public/images/glass-3.png";
import demo10 from "../../public/images/glass-4.png";
import demo11 from "../../public/images/glass-5.png";
import demo12 from "../../public/images/glass-6.png";
import { GlassCardProps } from "@/ts-definition/interfaces";

export const glassData: GlassCardProps[] = [
  {
    id: 1,
    image: demo1,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Alex Perry",
    model: "BAP0382B3 Optics",
    price: 1699,
    tag: "Best",
    colorCount: 3,
  },
  {
    id: 2,
    image: demo2,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Ray-Ban",
    model: "RB2132 New Wayfarer",
    price: 4999,
    tag: "Popular",
    colorCount: 5,
  },
  {
    id: 3,
    image: demo3,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Oakley",
    model: "OX3217 Socket 5.5",
    price: 4299,
    tag: "Trending",
    colorCount: 4,
  },
  {
    id: 4,
    image: demo4,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Tom Ford",
    model: "TF5505-B",
    price: 6899,
    colorCount: 2,
  },
  {
    id: 5,
    image: demo5,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Armani Exchange",
    model: "AX3025",
    price: 3599,
    tag: "New",
    colorCount: 6,
  },
  {
    id: 6,
    image: demo6,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Emporio Armani",
    model: "EA1052",
    price: 4499,
    colorCount: 3,
  },
  {
    id: 7,
    image: demo7,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Burberry",
    model: "BE1282",
    price: 5599,
    tag: "Luxury",
    colorCount: 3,
  },
  {
    id: 8,
    image: demo8,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Versace",
    model: "VE1234",
    price: 7299,
    tag: "Premium",
    colorCount: 4,
  },
  {
    id: 9,
    image: demo9,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Police",
    model: "VPLB23",
    price: 3799,
    colorCount: 2,
  },
  {
    id: 10,
    image: demo10,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Carrera",
    model: "CA6632",
    price: 4899,
    colorCount: 3,
  },
  {
    id: 11,
    image: demo11,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Fossil",
    model: "FOS7056",
    price: 2999,
    tag: "Budget",
    colorCount: 2,
  },
  {
    id: 12,
    image: demo12,
    images: [
      demo1,
      demo2,
      demo3,
      demo4,
      demo5,
      demo6,
      demo7,
      demo8,
      demo9,
      demo10,
      demo11,
      demo12,
    ],
    title: "Calvin Klein",
    model: "CK19506",
    price: 4199,
    colorCount: 3,
  },
];
