import { ILenseData } from "@/ts-definition/interfaces";
import lense1 from "../../public/images/lense-1.png";
import lense2 from "../../public/images/lense-2.png";
import lense3 from "../../public/images/lense-3.png";
import lense4 from "../../public/images/lense-4.png";

export const lenseData: ILenseData[] = [
  {
    badge: "Best",
    image: lense1,
    name: "Peacock Green Zero Power Dailies",
    brand: "Eyeline Optica",
    usageInfo: "Usage: 8H. 2 Lens per Box",
    price: 1699,
    originalPrice: 1899,
    discountPercentage: 15,
    discountLabel: "15% OFF",
  },
  {
    badge: "New",
    image: lense2,
    name: "Ocean Blue Monthly Power Lens",
    brand: "LensCraft",
    usageInfo: "Usage: 30 Days. 2 Lens per Box",
    price: 2499,
    originalPrice: 2799,
    discountPercentage: 11,
    discountLabel: "11% OFF",
  },
  {
    badge: "old",
    image: lense3,
    name: "Hazel Honey Colored Lens",
    brand: "VisionStyle",
    usageInfo: "Usage: 1 Day. 2 Lens per Box",
    price: 1199,
    originalPrice: 1499,
    discountPercentage: 20,
    discountLabel: "20% OFF",
  },
  {
    badge: "Limited",
    image: lense4,
    name: "Gray Mist Power Lens",
    brand: "OptiView",
    usageInfo: "Usage: 15 Days. 2 Lens per Box",
    price: 1999,
    originalPrice: 2299,
    discountPercentage: 13,
    discountLabel: "13% OFF",
  },
  {
    badge: "Best",
    image: lense1,
    name: "Peacock Green Zero Power Dailies",
    brand: "Eyeline Optica",
    usageInfo: "Usage: 8H. 2 Lens per Box",
    price: 1699,
    originalPrice: 1899,
    discountPercentage: 15,
    discountLabel: "15% OFF",
  },
  {
    badge: "New",
    image: lense2,
    name: "Ocean Blue Monthly Power Lens",
    brand: "LensCraft",
    usageInfo: "Usage: 30 Days. 2 Lens per Box",
    price: 2499,
    originalPrice: 2799,
    discountPercentage: 11,
    discountLabel: "11% OFF",
  },
  {
    badge: "old",
    image: lense3,
    name: "Hazel Honey Colored Lens",
    brand: "VisionStyle",
    usageInfo: "Usage: 1 Day. 2 Lens per Box",
    price: 1199,
    originalPrice: 1499,
    discountPercentage: 20,
    discountLabel: "20% OFF",
  },
  {
    badge: "Limited",
    image: lense4,
    name: "Gray Mist Power Lens",
    brand: "OptiView",
    usageInfo: "Usage: 15 Days. 2 Lens per Box",
    price: 1999,
    originalPrice: 2299,
    discountPercentage: 13,
    discountLabel: "13% OFF",
  },
  {
    badge: "Best",
    image: lense1,
    name: "Peacock Green Zero Power Dailies",
    brand: "Eyeline Optica",
    usageInfo: "Usage: 8H. 2 Lens per Box",
    price: 1699,
    originalPrice: 1899,
    discountPercentage: 15,
    discountLabel: "15% OFF",
  },
  {
    badge: "New",
    image: lense2,
    name: "Ocean Blue Monthly Power Lens",
    brand: "LensCraft",
    usageInfo: "Usage: 30 Days. 2 Lens per Box",
    price: 2499,
    originalPrice: 2799,
    discountPercentage: 11,
    discountLabel: "11% OFF",
  },
  {
    badge: "old",
    image: lense3,
    name: "Hazel Honey Colored Lens",
    brand: "VisionStyle",
    usageInfo: "Usage: 1 Day. 2 Lens per Box",
    price: 1199,
    originalPrice: 1499,
    discountPercentage: 20,
    discountLabel: "20% OFF",
  },
  {
    badge: "Limited",
    image: lense4,
    name: "Gray Mist Power Lens",
    brand: "OptiView",
    usageInfo: "Usage: 15 Days. 2 Lens per Box",
    price: 1999,
    originalPrice: 2299,
    discountPercentage: 13,
    discountLabel: "13% OFF",
  },
];
