import { TTelemedicineData } from "@/ts-definition/types";
import drAshrarVai from "../../public/images/telemedicine/telemedicine-eye-test.png";
import drKarim from "../../public/images/telemedicine/telemedicine-eye-test.png";
import drSharmin from "../../public/images/telemedicine/telemedicine-eye-test.png";

export const telemedicineData: TTelemedicineData[] = [
  {
    id: 1,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 4,
    img: drKarim,
    exp: 20,
    fee: 400,
  },
  {
    id: 2,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 4,
    img: drAshrarVai,
    exp: 10,
    fee: 400,
  },
  {
    id: 3,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 4,
    img: drSharmin,
    exp: 6,

    fee: 400,
  },
  {
    id: 4,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 5,
    img: drAshrarVai,
    exp: 15,
    fee: 400,
  },
  {
    id: 5,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 4,
    img: drAshrarVai,
    exp: 12,
    fee: 400,
  },
  {
    id: 6,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 5,
    img: drAshrarVai,
    exp: 8,

    fee: 400,
  },
  {
    id: 7,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 4,
    img: drAshrarVai,
    exp: 11,
    fee: 400,
  },
  {
    id: 8,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 5,
    img: drAshrarVai,
    exp: 18,
    fee: 400,
  },
  {
    id: 9,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 4,
    img: drAshrarVai,
    exp: 9,

    fee: 400,
  },
  {
    id: 10,
    name: "doctor-name",
    degree: "your-degree",
    post: "your-post",
    reviews: 5,
    img: drAshrarVai,
    exp: 14,
    fee: 400,
  },
];
